# Language and env

language: node_js
node_js: 
  - node # latest stable

# What is built

branches:
  only:
  - master

# Travis Lifecycle

install:
  - npm ci

jobs:
  include:
    - stage: test
    - script: echo "tests disabled" #npm test
    - stage: deploy
      if: branch = master && type != pull_request
    - script: npm run build-demo
      env: DEPLOY_TARGET_BRANCH=gh-pages
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./tools/deploy.sh
    - script: npm run build-preprod
      env: DEPLOY_TARGET_BRANCH=preprod-gironde.fr
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./tools/deploy.sh
    - script: npm run build-production
      env: DEPLOY_TARGET_BRANCH=gironde.fr
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./tools/deploy.sh



# Other configs

git:
  depth: 10
